In [1]:
# Install packages
%pip install pandas

# Import
import pandas as pd

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os

folder = r"C:\Users\Mahin\OneDrive\Desktop\Group 18-Phase 2"

print(os.listdir(folder))

df_311_data = pd.read_csv(os.path.join(folder, "311_data.csv"))
df_income_data = pd.read_csv(os.path.join(folder, "income_data.csv"))
df_zip_data = pd.read_csv(os.path.join(folder, "zip_shape.csv"))

print("311 data:")
display(df_311_data.head())

print("Income data:")
display(df_income_data.head())

print("ZIP shape data:")
display(df_zip_data.head())

['.venv', '311_data.csv', 'Cencus.ipynb', 'CIS 9655 (Spring 2026) Group Project Phase II.pdf', 'Gr18_ChowdhuryTabassumUangWu.pdf', 'income_data.csv', 'zip_shape.csv']

C:\Users\Mahin\AppData\Local\Temp\ipykernel_3664\717468911.py:7: DtypeWarning: Columns (0: Vehicle Type, 1: Taxi Company Borough, 2: Bridge Highway Name, 3: Bridge Highway Direction, 4: Road Ramp, 5: Bridge Highway Segment) have mixed types. Specify dtype option on import or set low_memory=False.
  df_311_data = pd.read_csv(os.path.join(folder, "311_data.csv"))

311 data:

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,59888160,12/31/2023 11:37:05 PM,01/01/2024 12:32:08 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,NaN,Street/Sidewalk,10466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.891850,-73.857488,POINT (-73.85748840323 40.89184992605)
1,59892669,12/31/2023 11:36:38 PM,12/31/2023 11:41:10 PM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,NaN,Street/Sidewalk,10036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.760301,-73.994982,POINT (-73.994982493324 40.760301271825)
2,59888957,12/31/2023 11:36:31 PM,12/31/2023 11:57:50 PM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.787323,-73.949880,POINT (-73.949880401232 40.78732340806)
3,59892052,12/31/2023 11:36:28 PM,01/19/2024 02:37:36 PM,EDC,Economic Development Corporation,Noise - Helicopter,Other,Flying Too Low,Above Address,10016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.741808,-73.980495,POINT (-73.980494894727 40.741808367174)
4,59890569,12/31/2023 11:35:57 PM,01/01/2024 12:44:26 AM,NYPD,New York City Police Department,Illegal Fireworks,NaN,NaN,Street/Sidewalk,11213,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.669100,-73.936657,POINT (-73.936656778562 40.669100245103)

Income data:

,GEO_ID,NAME,S1903_C01_001E,S1903_C01_001M,S1903_C01_002E,S1903_C01_002M,S1903_C01_003E,S1903_C01_003M,S1903_C01_004E,S1903_C01_004M,...,S1903_C03_036M,S1903_C03_037E,S1903_C03_037M,S1903_C03_038E,S1903_C03_038M,S1903_C03_039E,S1903_C03_039M,S1903_C03_040E,S1903_C03_040M,Unnamed: 242
0,Geography,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,NaN
1,0400000US36,New York,7668956,12766,4803522,12737,1069890,5637,33451,1330,...,444,102188,1577,59746,621,49047,620,114567,1579,NaN
2,860Z200US06390,ZCTA5 06390,17,13,17,13,0,13,0,13,...,**,-,**,-,**,-,**,-,**,NaN
3,860Z200US10001,ZCTA5 10001,15097,796,8810,675,1441,359,32,40,...,10860,"250,000+",***,156563,34367,107149,24995,234638,53290,NaN
4,860Z200US10002,ZCTA5 10002,35771,1265,12313,895,2821,474,92,70,...,5172,128973,34470,45394,9075,36743,5411,198188,29003,NaN

ZIP shape data:

,MODZCTA,label,ZCTA,pop_est,the_geom
0,10001,"10001, 10118","10001, 10119, 10199","23,072",MULTIPOLYGON (((-73.98774438827894 40.74406551...
1,10002,10002,10002,"74,993",MULTIPOLYGON (((-73.99750380833868 40.71407144...
2,10003,10003,10003,"54,682",MULTIPOLYGON (((-73.98863576728334 40.72293099...
3,10026,10026,10026,"39,363",MULTIPOLYGON (((-73.96200720826798 40.80550908...
4,10004,10004,10004,"3,028",MULTIPOLYGON (((-74.00826694529984 40.70771979...

In [3]:
# Keep only useful columns using your actual column names
df_311 = df_311_data[[
    'Created Date',
    'Closed Date',
    'Incident Zip',
    'Problem (formerly Complaint Type)',
    'Borough'
]].copy()

# Rename columns to simpler names
df_311 = df_311.rename(columns={
    'Created Date': 'created_date',
    'Closed Date': 'closed_date',
    'Incident Zip': 'zip_code',
    'Problem (formerly Complaint Type)': 'complaint_type',
    'Borough': 'borough'
})

# Convert dates
df_311['created_date'] = pd.to_datetime(df_311['created_date'], errors='coerce')
df_311['closed_date'] = pd.to_datetime(df_311['closed_date'], errors='coerce')

# Remove missing important values
df_311 = df_311.dropna(subset=['created_date', 'closed_date', 'zip_code'])

# Create resolution time in hours
df_311['resolution_time_hours'] = (
    df_311['closed_date'] - df_311['created_date']
).dt.total_seconds() / 3600

# Remove bad values
df_311 = df_311[
    (df_311['resolution_time_hours'] > 0) &
    (df_311['resolution_time_hours'] < 500)
]

# Clean ZIP code
df_311['zip_code'] = df_311['zip_code'].astype(str).str[:5]

# Check result
display(df_311.head())
print(df_311.shape)

C:\Users\Mahin\AppData\Local\Temp\ipykernel_3664\3793363055.py:20: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['created_date'] = pd.to_datetime(df_311['created_date'], errors='coerce')
C:\Users\Mahin\AppData\Local\Temp\ipykernel_3664\3793363055.py:21: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['closed_date'] = pd.to_datetime(df_311['closed_date'], errors='coerce')

,created_date,closed_date,zip_code,complaint_type,borough,resolution_time_hours
0,2023-12-31 23:37:05,2024-01-01 00:32:08,10466,Noise - Street/Sidewalk,BRONX,0.917500
1,2023-12-31 23:36:38,2023-12-31 23:41:10,10036,Noise - Street/Sidewalk,MANHATTAN,0.075556
2,2023-12-31 23:36:31,2023-12-31 23:57:50,10029,Noise - Residential,MANHATTAN,0.355278
3,2023-12-31 23:36:28,2024-01-19 14:37:36,10016,Noise - Helicopter,MANHATTAN,447.018889
4,2023-12-31 23:35:57,2024-01-01 00:44:26,11213,Illegal Fireworks,BROOKLYN,1.141389

(2680921, 6)

In [6]:
print(df_income_data.shape)
print(df_income_data.columns.tolist())
display(df_income_data.head())

(1826, 243)
['GEO_ID', 'NAME', 'S1903_C01_001E', 'S1903_C01_001M', 'S1903_C01_002E', 'S1903_C01_002M', 'S1903_C01_003E', 'S1903_C01_003M', 'S1903_C01_004E', 'S1903_C01_004M', 'S1903_C01_005E', 'S1903_C01_005M', 'S1903_C01_006E', 'S1903_C01_006M', 'S1903_C01_007E', 'S1903_C01_007M', 'S1903_C01_008E', 'S1903_C01_008M', 'S1903_C01_009E', 'S1903_C01_009M', 'S1903_C01_010E', 'S1903_C01_010M', 'S1903_C01_011E', 'S1903_C01_011M', 'S1903_C01_012E', 'S1903_C01_012M', 'S1903_C01_013E', 'S1903_C01_013M', 'S1903_C01_014E', 'S1903_C01_014M', 'S1903_C01_015E', 'S1903_C01_015M', 'S1903_C01_016E', 'S1903_C01_016M', 'S1903_C01_017E', 'S1903_C01_017M', 'S1903_C01_018E', 'S1903_C01_018M', 'S1903_C01_019E', 'S1903_C01_019M', 'S1903_C01_020E', 'S1903_C01_020M', 'S1903_C01_021E', 'S1903_C01_021M', 'S1903_C01_022E', 'S1903_C01_022M', 'S1903_C01_023E', 'S1903_C01_023M', 'S1903_C01_024E', 'S1903_C01_024M', 'S1903_C01_025E', 'S1903_C01_025M', 'S1903_C01_026E', 'S1903_C01_026M', 'S1903_C01_027E', 'S1903_C01_027M', 'S1903_C01_028E', 'S1903_C01_028M', 'S1903_C01_029E', 'S1903_C01_029M', 'S1903_C01_030E', 'S1903_C01_030M', 'S1903_C01_031E', 'S1903_C01_031M', 'S1903_C01_032E', 'S1903_C01_032M', 'S1903_C01_033E', 'S1903_C01_033M', 'S1903_C01_034E', 'S1903_C01_034M', 'S1903_C01_035E', 'S1903_C01_035M', 'S1903_C01_036E', 'S1903_C01_036M', 'S1903_C01_037E', 'S1903_C01_037M', 'S1903_C01_038E', 'S1903_C01_038M', 'S1903_C01_039E', 'S1903_C01_039M', 'S1903_C01_040E', 'S1903_C01_040M', 'S1903_C02_001E', 'S1903_C02_001M', 'S1903_C02_002E', 'S1903_C02_002M', 'S1903_C02_003E', 'S1903_C02_003M', 'S1903_C02_004E', 'S1903_C02_004M', 'S1903_C02_005E', 'S1903_C02_005M', 'S1903_C02_006E', 'S1903_C02_006M', 'S1903_C02_007E', 'S1903_C02_007M', 'S1903_C02_008E', 'S1903_C02_008M', 'S1903_C02_009E', 'S1903_C02_009M', 'S1903_C02_010E', 'S1903_C02_010M', 'S1903_C02_011E', 'S1903_C02_011M', 'S1903_C02_012E', 'S1903_C02_012M', 'S1903_C02_013E', 'S1903_C02_013M', 'S1903_C02_014E', 'S1903_C02_014M', 'S1903_C02_015E', 'S1903_C02_015M', 'S1903_C02_016E', 'S1903_C02_016M', 'S1903_C02_017E', 'S1903_C02_017M', 'S1903_C02_018E', 'S1903_C02_018M', 'S1903_C02_019E', 'S1903_C02_019M', 'S1903_C02_020E', 'S1903_C02_020M', 'S1903_C02_021E', 'S1903_C02_021M', 'S1903_C02_022E', 'S1903_C02_022M', 'S1903_C02_023E', 'S1903_C02_023M', 'S1903_C02_024E', 'S1903_C02_024M', 'S1903_C02_025E', 'S1903_C02_025M', 'S1903_C02_026E', 'S1903_C02_026M', 'S1903_C02_027E', 'S1903_C02_027M', 'S1903_C02_028E', 'S1903_C02_028M', 'S1903_C02_029E', 'S1903_C02_029M', 'S1903_C02_030E', 'S1903_C02_030M', 'S1903_C02_031E', 'S1903_C02_031M', 'S1903_C02_032E', 'S1903_C02_032M', 'S1903_C02_033E', 'S1903_C02_033M', 'S1903_C02_034E', 'S1903_C02_034M', 'S1903_C02_035E', 'S1903_C02_035M', 'S1903_C02_036E', 'S1903_C02_036M', 'S1903_C02_037E', 'S1903_C02_037M', 'S1903_C02_038E', 'S1903_C02_038M', 'S1903_C02_039E', 'S1903_C02_039M', 'S1903_C02_040E', 'S1903_C02_040M', 'S1903_C03_001E', 'S1903_C03_001M', 'S1903_C03_002E', 'S1903_C03_002M', 'S1903_C03_003E', 'S1903_C03_003M', 'S1903_C03_004E', 'S1903_C03_004M', 'S1903_C03_005E', 'S1903_C03_005M', 'S1903_C03_006E', 'S1903_C03_006M', 'S1903_C03_007E', 'S1903_C03_007M', 'S1903_C03_008E', 'S1903_C03_008M', 'S1903_C03_009E', 'S1903_C03_009M', 'S1903_C03_010E', 'S1903_C03_010M', 'S1903_C03_011E', 'S1903_C03_011M', 'S1903_C03_012E', 'S1903_C03_012M', 'S1903_C03_013E', 'S1903_C03_013M', 'S1903_C03_014E', 'S1903_C03_014M', 'S1903_C03_015E', 'S1903_C03_015M', 'S1903_C03_016E', 'S1903_C03_016M', 'S1903_C03_017E', 'S1903_C03_017M', 'S1903_C03_018E', 'S1903_C03_018M', 'S1903_C03_019E', 'S1903_C03_019M', 'S1903_C03_020E', 'S1903_C03_020M', 'S1903_C03_021E', 'S1903_C03_021M', 'S1903_C03_022E', 'S1903_C03_022M', 'S1903_C03_023E', 'S1903_C03_023M', 'S1903_C03_024E', 'S1903_C03_024M', 'S1903_C03_025E', 'S1903_C03_025M', 'S1903_C03_026E', 'S1903_C03_026M', 'S1903_C03_027E', 'S1903_C03_027M', 'S1903_C03_028E', 'S1903_C03_028M', 'S1903_C03_029E', 'S1903_C03_029M', 'S1903_C03_030E', 'S1903_C03_030M', 'S1903_C03_031E', 'S1903_C03_031M', 'S1903_C03_032E', 'S1903_C03_032M', 'S1903_C03_033E', 'S1903_C03_033M', 'S1903_C03_034E', 'S1903_C03_034M', 'S1903_C03_035E', 'S1903_C03_035M', 'S1903_C03_036E', 'S1903_C03_036M', 'S1903_C03_037E', 'S1903_C03_037M', 'S1903_C03_038E', 'S1903_C03_038M', 'S1903_C03_039E', 'S1903_C03_039M', 'S1903_C03_040E', 'S1903_C03_040M', 'Unnamed: 242']

,GEO_ID,NAME,S1903_C01_001E,S1903_C01_001M,S1903_C01_002E,S1903_C01_002M,S1903_C01_003E,S1903_C01_003M,S1903_C01_004E,S1903_C01_004M,...,S1903_C03_036M,S1903_C03_037E,S1903_C03_037M,S1903_C03_038E,S1903_C03_038M,S1903_C03_039E,S1903_C03_039M,S1903_C03_040E,S1903_C03_040M,Unnamed: 242
0,Geography,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,Estimate!!Number!!HOUSEHOLD INCOME BY RACE AND...,Margin of Error!!Number!!HOUSEHOLD INCOME BY R...,...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,Estimate!!Median income (dollars)!!NONFAMILY H...,Margin of Error!!Median income (dollars)!!NONF...,NaN
1,0400000US36,New York,7668956,12766,4803522,12737,1069890,5637,33451,1330,...,444,102188,1577,59746,621,49047,620,114567,1579,NaN
2,860Z200US06390,ZCTA5 06390,17,13,17,13,0,13,0,13,...,**,-,**,-,**,-,**,-,**,NaN
3,860Z200US10001,ZCTA5 10001,15097,796,8810,675,1441,359,32,40,...,10860,"250,000+",***,156563,34367,107149,24995,234638,53290,NaN
4,860Z200US10002,ZCTA5 10002,35771,1265,12313,895,2821,474,92,70,...,5172,128973,34470,45394,9075,36743,5411,198188,29003,NaN

In [7]:
# Reload income data
df_income_data = pd.read_csv("income_data.csv")

# Show columns
print(df_income_data.columns.tolist())

# Find ZIP column
zip_col = "NAME"

# Find the median household income column automatically
income_cols = [col for col in df_income_data.columns if "S1903_C03_001E" in col or "Median income" in col]

print("Possible income columns:", income_cols)

['GEO_ID', 'NAME', 'S1903_C01_001E', 'S1903_C01_001M', 'S1903_C01_002E', 'S1903_C01_002M', 'S1903_C01_003E', 'S1903_C01_003M', 'S1903_C01_004E', 'S1903_C01_004M', 'S1903_C01_005E', 'S1903_C01_005M', 'S1903_C01_006E', 'S1903_C01_006M', 'S1903_C01_007E', 'S1903_C01_007M', 'S1903_C01_008E', 'S1903_C01_008M', 'S1903_C01_009E', 'S1903_C01_009M', 'S1903_C01_010E', 'S1903_C01_010M', 'S1903_C01_011E', 'S1903_C01_011M', 'S1903_C01_012E', 'S1903_C01_012M', 'S1903_C01_013E', 'S1903_C01_013M', 'S1903_C01_014E', 'S1903_C01_014M', 'S1903_C01_015E', 'S1903_C01_015M', 'S1903_C01_016E', 'S1903_C01_016M', 'S1903_C01_017E', 'S1903_C01_017M', 'S1903_C01_018E', 'S1903_C01_018M', 'S1903_C01_019E', 'S1903_C01_019M', 'S1903_C01_020E', 'S1903_C01_020M', 'S1903_C01_021E', 'S1903_C01_021M', 'S1903_C01_022E', 'S1903_C01_022M', 'S1903_C01_023E', 'S1903_C01_023M', 'S1903_C01_024E', 'S1903_C01_024M', 'S1903_C01_025E', 'S1903_C01_025M', 'S1903_C01_026E', 'S1903_C01_026M', 'S1903_C01_027E', 'S1903_C01_027M', 'S1903_C01_028E', 'S1903_C01_028M', 'S1903_C01_029E', 'S1903_C01_029M', 'S1903_C01_030E', 'S1903_C01_030M', 'S1903_C01_031E', 'S1903_C01_031M', 'S1903_C01_032E', 'S1903_C01_032M', 'S1903_C01_033E', 'S1903_C01_033M', 'S1903_C01_034E', 'S1903_C01_034M', 'S1903_C01_035E', 'S1903_C01_035M', 'S1903_C01_036E', 'S1903_C01_036M', 'S1903_C01_037E', 'S1903_C01_037M', 'S1903_C01_038E', 'S1903_C01_038M', 'S1903_C01_039E', 'S1903_C01_039M', 'S1903_C01_040E', 'S1903_C01_040M', 'S1903_C02_001E', 'S1903_C02_001M', 'S1903_C02_002E', 'S1903_C02_002M', 'S1903_C02_003E', 'S1903_C02_003M', 'S1903_C02_004E', 'S1903_C02_004M', 'S1903_C02_005E', 'S1903_C02_005M', 'S1903_C02_006E', 'S1903_C02_006M', 'S1903_C02_007E', 'S1903_C02_007M', 'S1903_C02_008E', 'S1903_C02_008M', 'S1903_C02_009E', 'S1903_C02_009M', 'S1903_C02_010E', 'S1903_C02_010M', 'S1903_C02_011E', 'S1903_C02_011M', 'S1903_C02_012E', 'S1903_C02_012M', 'S1903_C02_013E', 'S1903_C02_013M', 'S1903_C02_014E', 'S1903_C02_014M', 'S1903_C02_015E', 'S1903_C02_015M', 'S1903_C02_016E', 'S1903_C02_016M', 'S1903_C02_017E', 'S1903_C02_017M', 'S1903_C02_018E', 'S1903_C02_018M', 'S1903_C02_019E', 'S1903_C02_019M', 'S1903_C02_020E', 'S1903_C02_020M', 'S1903_C02_021E', 'S1903_C02_021M', 'S1903_C02_022E', 'S1903_C02_022M', 'S1903_C02_023E', 'S1903_C02_023M', 'S1903_C02_024E', 'S1903_C02_024M', 'S1903_C02_025E', 'S1903_C02_025M', 'S1903_C02_026E', 'S1903_C02_026M', 'S1903_C02_027E', 'S1903_C02_027M', 'S1903_C02_028E', 'S1903_C02_028M', 'S1903_C02_029E', 'S1903_C02_029M', 'S1903_C02_030E', 'S1903_C02_030M', 'S1903_C02_031E', 'S1903_C02_031M', 'S1903_C02_032E', 'S1903_C02_032M', 'S1903_C02_033E', 'S1903_C02_033M', 'S1903_C02_034E', 'S1903_C02_034M', 'S1903_C02_035E', 'S1903_C02_035M', 'S1903_C02_036E', 'S1903_C02_036M', 'S1903_C02_037E', 'S1903_C02_037M', 'S1903_C02_038E', 'S1903_C02_038M', 'S1903_C02_039E', 'S1903_C02_039M', 'S1903_C02_040E', 'S1903_C02_040M', 'S1903_C03_001E', 'S1903_C03_001M', 'S1903_C03_002E', 'S1903_C03_002M', 'S1903_C03_003E', 'S1903_C03_003M', 'S1903_C03_004E', 'S1903_C03_004M', 'S1903_C03_005E', 'S1903_C03_005M', 'S1903_C03_006E', 'S1903_C03_006M', 'S1903_C03_007E', 'S1903_C03_007M', 'S1903_C03_008E', 'S1903_C03_008M', 'S1903_C03_009E', 'S1903_C03_009M', 'S1903_C03_010E', 'S1903_C03_010M', 'S1903_C03_011E', 'S1903_C03_011M', 'S1903_C03_012E', 'S1903_C03_012M', 'S1903_C03_013E', 'S1903_C03_013M', 'S1903_C03_014E', 'S1903_C03_014M', 'S1903_C03_015E', 'S1903_C03_015M', 'S1903_C03_016E', 'S1903_C03_016M', 'S1903_C03_017E', 'S1903_C03_017M', 'S1903_C03_018E', 'S1903_C03_018M', 'S1903_C03_019E', 'S1903_C03_019M', 'S1903_C03_020E', 'S1903_C03_020M', 'S1903_C03_021E', 'S1903_C03_021M', 'S1903_C03_022E', 'S1903_C03_022M', 'S1903_C03_023E', 'S1903_C03_023M', 'S1903_C03_024E', 'S1903_C03_024M', 'S1903_C03_025E', 'S1903_C03_025M', 'S1903_C03_026E', 'S1903_C03_026M', 'S1903_C03_027E', 'S1903_C03_027M', 'S1903_C03_028E', 'S1903_C03_028M', 'S1903_C03_029E', 'S1903_C03_029M', 'S1903_C03_030E', 'S1903_C03_030M', 'S1903_C03_031E', 'S1903_C03_031M', 'S1903_C03_032E', 'S1903_C03_032M', 'S1903_C03_033E', 'S1903_C03_033M', 'S1903_C03_034E', 'S1903_C03_034M', 'S1903_C03_035E', 'S1903_C03_035M', 'S1903_C03_036E', 'S1903_C03_036M', 'S1903_C03_037E', 'S1903_C03_037M', 'S1903_C03_038E', 'S1903_C03_038M', 'S1903_C03_039E', 'S1903_C03_039M', 'S1903_C03_040E', 'S1903_C03_040M', 'Unnamed: 242']
Possible income columns: ['S1903_C03_001E']

In [8]:
df_income = df_income_data[["NAME", "S1903_C03_001E"]].copy()

df_income.columns = ["zip_code", "median_income"]

df_income["zip_code"] = df_income["zip_code"].astype(str).str.replace("ZCTA5 ", "", regex=False)
df_income["median_income"] = pd.to_numeric(df_income["median_income"], errors="coerce")

df_income = df_income.dropna()

print(df_income.shape)
display(df_income.head())

(1611, 2)

   zip_code  median_income
1  New York        84578.0
2     06390        51964.0
3     10001       123393.0
4     10002        46525.0
5     10003       153750.0

In [9]:
df_income = df_income[df_income["zip_code"] != "New York"]

In [9]:
df_merged = df_311.merge(df_income, on="zip_code")

print(df_merged.shape)
display(df_merged.head())

(2672411, 7)

,created_date,closed_date,zip_code,complaint_type,borough,resolution_time_hours,median_income
0,2023-12-31 23:37:05,2024-01-01 00:32:08,10466,Noise - Street/Sidewalk,BRONX,0.917500,66328.0
1,2023-12-31 23:36:38,2023-12-31 23:41:10,10036,Noise - Street/Sidewalk,MANHATTAN,0.075556,100225.0
2,2023-12-31 23:36:31,2023-12-31 23:57:50,10029,Noise - Residential,MANHATTAN,0.355278,38308.0
3,2023-12-31 23:36:28,2024-01-19 14:37:36,10016,Noise - Helicopter,MANHATTAN,447.018889,153065.0
4,2023-12-31 23:35:57,2024-01-01 00:44:26,11213,Illegal Fireworks,BROOKLYN,1.141389,62040.0

In [10]:
df_merged["income_group"] = pd.qcut(
    df_merged["median_income"],
    q=3,
    labels=["Low Income", "Middle Income", "High Income"]
)

display(df_merged.head())
print(df_merged["income_group"].value_counts())

,created_date,closed_date,zip_code,complaint_type,borough,resolution_time_hours,median_income,income_group
0,2023-12-31 23:37:05,2024-01-01 00:32:08,10466,Noise - Street/Sidewalk,BRONX,0.917500,66328.0,Middle Income
1,2023-12-31 23:36:38,2023-12-31 23:41:10,10036,Noise - Street/Sidewalk,MANHATTAN,0.075556,100225.0,High Income
2,2023-12-31 23:36:31,2023-12-31 23:57:50,10029,Noise - Residential,MANHATTAN,0.355278,38308.0,Low Income
3,2023-12-31 23:36:28,2024-01-19 14:37:36,10016,Noise - Helicopter,MANHATTAN,447.018889,153065.0,High Income
4,2023-12-31 23:35:57,2024-01-01 00:44:26,11213,Illegal Fireworks,BROOKLYN,1.141389,62040.0,Low Income

income_group
Low Income       897571
Middle Income    889000
High Income      885840
Name: count, dtype: int64

In [11]:
# Aggregate by ZIP
df_zip_agg = df_merged.groupby("zip_code").agg({
    "resolution_time_hours": "mean",
    "median_income": "first"
}).reset_index()

df_zip_agg.columns = ["zip_code", "avg_resolution_time", "median_income"]

display(df_zip_agg.head())
print(df_zip_agg.shape)

  zip_code  avg_resolution_time  median_income
0    10001            40.548726       123393.0
1    10002            40.522793        46525.0
2    10003            42.041470       153750.0
3    10004            23.177423       220592.0
4    10005            36.933852       211810.0

(182, 3)

In [4]:
%pip install plotly

Requirement already satisfied: plotly in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from plotly) (2.20.0)
Requirement already satisfied: packaging in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
df_zip_agg = df_merged.groupby("zip_code").agg({
    "resolution_time_hours": "mean",
    "median_income": "mean"
}).reset_index()

df_zip_agg.columns = ["zip_code", "avg_resolution_time", "median_income"]

In [13]:
# Install required packages
%pip install plotly nbformat

# Imports
import pandas as pd
import plotly.express as px

# Re-create ZIP aggregation
df_zip_agg = df_merged.groupby("zip_code").agg({
    "resolution_time_hours": "mean",
    "median_income": "mean"
}).reset_index()

df_zip_agg.columns = ["zip_code", "avg_resolution_time", "median_income"]

# Make sure ZIP is clean text
df_zip_agg["zip_code"] = df_zip_agg["zip_code"].astype(str).str.zfill(5)

# Preview aggregated data
display(df_zip_agg.head())
print(df_zip_agg.shape)

# Create map
fig = px.choropleth(
    df_zip_agg,
    geojson="https://raw.githubusercontent.com/OpenDataDE/State-zip-code-GeoJSON/master/ny_new_york_zip_codes_geo.min.json",
    locations="zip_code",
    featureidkey="properties.ZCTA5CE10",
    color="avg_resolution_time",
    color_continuous_scale="RdYlGn_r",
    labels={
        "avg_resolution_time": "Avg Resolution Time (Hours)",
        "median_income": "Median Income"
    },
    hover_data={
        "zip_code": True,
        "avg_resolution_time": ":.2f",
        "median_income": ":,.0f"
    },
    title="Average 311 Resolution Time by ZIP Code"
)

fig.update_geos(
    fitbounds="locations",
    visible=False
)

fig.update_layout(
    margin={"r": 0, "t": 50, "l": 0, "b": 0},
    height=650
)

fig.show()

Requirement already satisfied: plotly in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (6.7.0)
Requirement already satisfied: nbformat in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (5.10.4)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from plotly) (2.20.0)
Requirement already satisfied: packaging in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from plotly) (26.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  zip_code  avg_resolution_time  median_income
0    10001            40.548726       123393.0
1    10002            40.522793        46525.0
2    10003            42.041470       153750.0
3    10004            23.177423       220592.0
4    10005            36.933852       211810.0

(182, 3)

In [14]:
%pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from statsmodels) (2.4.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from statsmodels) (3.0.2)
Requirement already satisfied: patsy>=0.5.6 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from statsmodels) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\mahin\onedrive\desktop\group 18-phase 2\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import plotly.express as px

df_scatter = df_merged.groupby("zip_code").agg({
    "median_income": "mean",
    "resolution_time_hours": "mean"
}).reset_index()

fig2 = px.scatter(
    df_scatter,
    x="median_income",
    y="resolution_time_hours",
    trendline="ols",
    title="Median Income vs Average Resolution Time",
    labels={
        "median_income": "Median Household Income ($)",
        "resolution_time_hours": "Avg Resolution Time (Hours)"
    }
)

fig2.show()

This scatterplot shows the relationship between median income and average 311 resolution time at the ZIP code level. The trendline slopes slightly downward, suggesting that higher-income neighborhoods may receive somewhat faster service. However, the relationship is relatively weak, indicating that income alone does not strongly determine service speed.

In [16]:
# Create month column
df_merged["month"] = df_merged["created_date"].dt.to_period("M").astype(str)

# Aggregate by month + income group
df_time = df_merged.groupby(["month", "income_group"]).agg({
    "resolution_time_hours": "mean"
}).reset_index()

# Plot
fig3 = px.line(
    df_time,
    x="month",
    y="resolution_time_hours",
    color="income_group",
    title="311 Resolution Time Trends Over Time by Income Group",
    labels={
        "resolution_time_hours": "Avg Resolution Time (Hours)",
        "month": "Month",
        "income_group": "Income Group"
    }
)

fig3.show()

This chart shows how resolution times change over time across income groups. Low-income neighborhoods consistently experience longer resolution times, while high-income areas tend to receive faster service. This suggests a persistent service gap over time.

In [17]:
import pandas as pd
import plotly.express as px

top_complaints = df_merged["complaint_type"].value_counts().head(5).index

df_bar = df_merged[df_merged["complaint_type"].isin(top_complaints)].copy()

df_bar = df_bar.groupby(["complaint_type", "income_group"]).agg({
    "resolution_time_hours": "mean"
}).reset_index()

df_bar["complaint_type"] = df_bar["complaint_type"].str.title()

# FIX: enforce correct income order
df_bar["income_group"] = pd.Categorical(
    df_bar["income_group"],
    categories=["Low Income", "Middle Income", "High Income"],
    ordered=True
)

# SORT properly
df_bar = df_bar.sort_values(["complaint_type", "income_group"])

fig4 = px.bar(
    df_bar,
    x="complaint_type",
    y="resolution_time_hours",
    color="income_group",
    barmode="group",
    title="Average 311 Resolution Time by Complaint Type and Income Group",
    labels={
        "resolution_time_hours": "Avg Resolution Time (Hours)",
        "complaint_type": "Complaint Type",
        "income_group": "Income Group"
    },
    color_discrete_map={
        "Low Income": "#d62728",
        "Middle Income": "#ff7f0e",
        "High Income": "#2ca02c"
    },
    category_orders={
        "income_group": ["Low Income", "Middle Income", "High Income"]
    }
)

fig4.update_traces(
    texttemplate="%{y:.1f}",
    textposition="outside"
)

fig4.update_layout(
    xaxis_tickangle=-45,
    height=550,
    margin=dict(l=40, r=40, t=70, b=90),
    legend_title="Income Group"
)

fig4.show()

In [21]:
from dash import Dash, dcc, html, Input, Output
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

geojson_url = "https://raw.githubusercontent.com/OpenDataDE/State-zip-code-GeoJSON/master/ny_new_york_zip_codes_geo.min.json"

app = Dash(__name__)

borough_options = sorted(df_merged["borough"].dropna().unique())
income_options = ["Low Income", "Middle Income", "High Income"]
complaint_options = df_merged["complaint_type"].value_counts().head(5).index.tolist()

def filter_data(selected_boroughs, selected_complaints, selected_income, start_date, end_date):
    dff = df_merged.copy()

    dff = dff[
        (dff["created_date"] >= pd.to_datetime(start_date)) &
        (dff["created_date"] <= pd.to_datetime(end_date))
    ]

    if selected_boroughs:
        dff = dff[dff["borough"].isin(selected_boroughs)]

    if selected_complaints:
        dff = dff[dff["complaint_type"].isin(selected_complaints)]

    if selected_income:
        dff = dff[dff["income_group"].isin(selected_income)]

    return dff


def make_map(dff):
    all_zip = df_merged.groupby("zip_code").agg({
        "resolution_time_hours": "mean"
    }).reset_index()

    selected_zip = dff.groupby("zip_code").agg({
        "resolution_time_hours": "mean",
        "median_income": "mean"
    }).reset_index()

    base = go.Choropleth(
        geojson=geojson_url,
        locations=all_zip["zip_code"],
        z=[1] * len(all_zip),
        featureidkey="properties.ZCTA5CE10",
        colorscale=[[0, "#d9d9d9"], [1, "#d9d9d9"]],
        showscale=False,
        marker_line_color="white",
        marker_line_width=0.4,
        hoverinfo="skip"
    )

    color = go.Choropleth(
        geojson=geojson_url,
        locations=selected_zip["zip_code"],
        z=selected_zip["resolution_time_hours"],
        featureidkey="properties.ZCTA5CE10",
        colorscale="RdYlGn_r",
        marker_line_color="white",
        marker_line_width=0.5,
        colorbar=dict(
            title="Avg Resolution<br>Time (Hours)",
            thickness=12,
            len=0.55,
            x=0.92,
            y=0.50
        ),
        hovertemplate=
            "ZIP: %{location}<br>" +
            "Avg Resolution Time: %{z:.1f} hours<br>" +
            "<extra></extra>"
    )

    fig_map = go.Figure(data=[base, color])

    fig_map.update_geos(
        fitbounds="locations",
        visible=False
    )

    fig_map.update_layout(
        title="Average 311 Resolution Time by ZIP Code",
        height=330,
        margin=dict(l=5, r=5, t=35, b=5)
    )

    return fig_map


def make_scatter(dff):
    df_scatter = dff.groupby(["zip_code", "borough"]).agg({
        "median_income": "mean",
        "resolution_time_hours": "mean"
    }).reset_index()

    fig_scatter = px.scatter(
        df_scatter,
        x="median_income",
        y="resolution_time_hours",
        color="borough",
        trendline="ols",
        title="Median Income vs Average Resolution Time",
        labels={
            "median_income": "Median Household Income ($)",
            "resolution_time_hours": "Avg Resolution Time (Hours)",
            "borough": "Borough"
        }
    )

    fig_scatter.update_layout(height=330, margin=dict(l=40, r=10, t=35, b=40))
    return fig_scatter


def make_time(dff):
    dff = dff.copy()
    dff["month"] = dff["created_date"].dt.to_period("M").astype(str)

    df_time = dff.groupby(["month", "income_group"]).agg({
        "resolution_time_hours": "mean"
    }).reset_index()

    fig_time = px.line(
        df_time,
        x="month",
        y="resolution_time_hours",
        color="income_group",
        title="311 Resolution Time Trends Over Time by Income Group",
        labels={
            "resolution_time_hours": "Avg Resolution Time (Hours)",
            "month": "Month",
            "income_group": "Income Group"
        },
        color_discrete_map={
            "Low Income": "#d62728",
            "Middle Income": "#ff7f0e",
            "High Income": "#2ca02c"
        }
    )

    fig_time.update_layout(height=230, margin=dict(l=40, r=10, t=35, b=35))
    return fig_time


def make_bar(dff):
    df_bar = dff[dff["complaint_type"].isin(complaint_options)].copy()

    df_bar = df_bar.groupby(["complaint_type", "income_group"]).agg({
        "resolution_time_hours": "mean"
    }).reset_index()

    df_bar["complaint_type"] = df_bar["complaint_type"].str.title()

    fig_bar = px.bar(
        df_bar,
        x="complaint_type",
        y="resolution_time_hours",
        color="income_group",
        barmode="group",
        title="Average Resolution Time by Complaint Type and Income Group",
        labels={
            "resolution_time_hours": "Avg Resolution Time (Hours)",
            "complaint_type": "Complaint Type",
            "income_group": "Income Group"
        },
        color_discrete_map={
            "Low Income": "#d62728",
            "Middle Income": "#ff7f0e",
            "High Income": "#2ca02c"
        },
        category_orders={
            "income_group": ["Low Income", "Middle Income", "High Income"]
        }
    )

    fig_bar.update_traces(texttemplate="%{y:.1f}", textposition="outside")
    fig_bar.update_layout(
        xaxis_tickangle=-45,
        height=260,
        margin=dict(l=40, r=10, t=35, b=70),
        legend_title="Income Group"
    )

    return fig_bar


card_style = {
    "border": "1px solid #bfc7d1",
    "backgroundColor": "white",
    "padding": "6px",
    "boxSizing": "border-box"
}

header_style = {
    "backgroundColor": "#06264a",
    "color": "white",
    "textAlign": "center",
    "fontWeight": "bold",
    "padding": "5px",
    "fontSize": "14px"
}

insight_bottom_style = {
    "fontSize": "12px",
    "lineHeight": "1.35",
    "padding": "8px",
    "backgroundColor": "white",
    "borderTop": "1px solid #bfc7d1"
}

app.layout = html.Div([

    html.Div([
        html.H1("NYC 311 SERVICE EQUITY DASHBOARD", style={"margin": "0", "fontSize": "28px"}),
        html.Div(
            "Do wealthier neighborhoods receive faster resolution times for similar 311 complaints in New York City?",
            style={"fontStyle": "italic", "fontSize": "15px", "marginTop": "4px"}
        )
    ], style={
        "backgroundColor": "#06264a",
        "color": "white",
        "textAlign": "center",
        "padding": "15px",
        "fontFamily": "Arial"
    }),

    html.Div([

        html.Div([
            html.H3("FILTERS", style={"textAlign": "center", "fontSize": "16px"}),

            html.Label("Borough", style={"fontWeight": "bold"}),
            dcc.Checklist(
                id="borough_filter",
                options=[{"label": b.title(), "value": b} for b in borough_options],
                value=borough_options,
                style={"fontSize": "11px", "marginTop": "8px", "marginBottom": "18px"},
                inputStyle={"marginRight": "5px"}
            ),

            html.Label("Complaint Type", style={"fontWeight": "bold"}),
            dcc.Checklist(
                id="complaint_filter",
                options=[{"label": c.title(), "value": c} for c in complaint_options],
                value=complaint_options,
                style={"fontSize": "11px", "marginTop": "8px", "marginBottom": "18px"},
                inputStyle={"marginRight": "5px"}
            ),

            html.Label("Date Range", style={"fontWeight": "bold"}),
            dcc.DatePickerRange(
                id="date_filter",
                start_date=df_merged["created_date"].min(),
                end_date=df_merged["created_date"].max(),
                display_format="M/D/YYYY",
                style={"fontSize": "11px", "marginBottom": "18px"}
            ),

            html.Br(),
            html.Br(),

            html.Label("Income Group", style={"fontWeight": "bold"}),
            dcc.Checklist(
                id="income_filter",
                options=[{"label": i, "value": i} for i in income_options],
                value=income_options,
                style={"fontSize": "11px", "marginTop": "8px"},
                inputStyle={"marginRight": "5px"}
            )

        ], style={
            "width": "190px",
            "minWidth": "190px",
            "backgroundColor": "#f2f4f7",
            "padding": "12px",
            "borderRight": "1px solid #bfc7d1",
            "fontFamily": "Arial",
            "fontSize": "12px",
            "minHeight": "900px"
        }),

        html.Div([

            html.Div([

                html.Div([
                    html.Div("1. AVERAGE 311 RESOLUTION TIME BY ZIP CODE", style=header_style),
                    dcc.Graph(id="map_chart", config={"displayModeBar": False}),
                    html.Div([
                        html.B("What it shows: "),
                        html.Span("Average resolution time across NYC ZIP codes. "),
                        html.Br(),
                        html.B("Purpose: "),
                        html.Span("Identify where services are faster or slower geographically. "),
                        html.Br(),
                        html.B("Example insight: "),
                        html.Span("Some ZIP codes have much longer resolution times than others.")
                    ], style=insight_bottom_style)
                ], style={**card_style, "width": "50%"}),

                html.Div([
                    html.Div("2. MEDIAN INCOME VS AVERAGE RESOLUTION TIME", style=header_style),
                    dcc.Graph(id="scatter_chart", config={"displayModeBar": False}),
                    html.Div([
                        html.B("What it shows: "),
                        html.Span("Relationship between income and resolution time by ZIP code. "),
                        html.Br(),
                        html.B("Purpose: "),
                        html.Span("Determine whether higher-income areas receive faster service. "),
                        html.Br(),
                        html.B("Example insight: "),
                        html.Span("The downward trend suggests wealthier areas may receive somewhat faster service.")
                    ], style=insight_bottom_style)
                ], style={**card_style, "width": "50%"})

            ], style={"display": "flex", "gap": "8px", "marginBottom": "8px"}),

            html.Div([
                html.Div("3. 311 RESOLUTION TIME TRENDS OVER TIME BY INCOME GROUP", style=header_style),
                dcc.Graph(id="time_chart", config={"displayModeBar": False}),
                html.Div([
                    html.B("What it shows: "),
                    html.Span("Change in resolution time over time by income group. "),
                    html.Br(),
                    html.B("Purpose: "),
                    html.Span("See if the gap between income groups is persistent. "),
                    html.Br(),
                    html.B("Example insight: "),
                    html.Span("Low-income areas often show longer resolution times.")
                ], style=insight_bottom_style)
            ], style={**card_style, "marginBottom": "8px"}),

            html.Div([
                html.Div("4. AVERAGE RESOLUTION TIME BY COMPLAINT TYPE AND INCOME GROUP", style=header_style),
                dcc.Graph(id="bar_chart", config={"displayModeBar": False}),
                html.Div([
                    html.B("What it shows: "),
                    html.Span("Resolution time across complaint types by income group. "),
                    html.Br(),
                    html.B("Purpose: "),
                    html.Span("Identify which complaint types show the biggest inequality. "),
                    html.Br(),
                    html.B("Example insight: "),
                    html.Span("Heat/Hot Water shows the largest resolution-time difference.")
                ], style=insight_bottom_style)
            ], style=card_style)

        ], style={
            "flex": "1",
            "padding": "8px",
            "backgroundColor": "white",
            "fontFamily": "Arial"
        })

    ], style={"display": "flex"}),

    html.Div([
        html.B("Overall Story: "),
        html.Span(
            "The map shows where response times are slower or faster. "
            "The scatterplot shows whether income is associated with those differences. "
            "The time-series shows how the pattern changes over time. "
            "The bar chart highlights which complaint types are most affected."
        )
    ], style={
        "backgroundColor": "#f2f4f7",
        "border": "1px solid #bfc7d1",
        "padding": "10px",
        "fontFamily": "Arial",
        "fontSize": "13px"
    })

], style={
    "maxWidth": "1450px",
    "margin": "0 auto",
    "backgroundColor": "white"
})


@app.callback(
    Output("map_chart", "figure"),
    Output("scatter_chart", "figure"),
    Output("time_chart", "figure"),
    Output("bar_chart", "figure"),
    Input("borough_filter", "value"),
    Input("complaint_filter", "value"),
    Input("income_filter", "value"),
    Input("date_filter", "start_date"),
    Input("date_filter", "end_date")
)
def update_dashboard(selected_boroughs, selected_complaints, selected_income, start_date, end_date):
    dff = filter_data(selected_boroughs, selected_complaints, selected_income, start_date, end_date)

    return (
        make_map(dff),
        make_scatter(dff),
        make_time(dff),
        make_bar(dff)
    )


app.run(debug=True)